### ISSUE TITLE
Correction for chapter 3 question 6

### ISSUE THREAD

**Issue by bh4ll4** [nimeshneema/UNIX-Concepts-and-Applications#2]
The solution provided for chapter 3 question 6 is not correct ,No new process will be shown , when you again run the ps command after you run the script command, because when you run the script command actually a new shell and a new shell and a new terminal is born and you are writing the ps command in this new terminal, although the terminal window remains same , so there is no script process running in this new terminal thats why it just shows only two processes the process for bash and the process for ps itself .Your answer is correct with reference to the parent shell but it is not specified anywhere so it might seem confusing to the first time reader, Also can you plzz tell how to check the processes here with respect to parent shell itself and not to the child shell

**Comment by nimeshneema** [comment]
Thanks for writing @bh4ll4. I'll soon take out some time, research it, and update the answer. Can you can please leave this issue open for the time being. I'll update you after improving the answer. Thank you. 🙏🏻

**Comment by bh4ll4** [comment]
Ya sure thing man

**Comment by nimeshneema** [comment]
Let me take a look into this issue as well.

**Comment by nimeshneema** [comment]
@bh4ll4 Please find my response below.

The current version of the answer reads:

> Running `script` command spawns a new sub-shell process.

Your querie:

> 1. No new process will be shown

A new process will be shown in the output of the `ps` command. The same can be identified with the different `PID` in the command's output. The output in this scenario differs between macOS and Ubuntu Linux. A sample output for both the platforms is quoted below:

**macOS**

```
16-MacBook-Pro:~ nimeshneema$ ps
  PID TTY           TIME CMD
 6102 ttys001    0:00.05 -bash
16-MacBook-Pro:~ nimeshneema$ script
Script started, output file is typescript
bash-5.0$ ps
  PID TTY           TIME CMD
 7609 ttys000    0:00.01 /usr/local/bin/bash -i
 6102 ttys001    0:00.05 -bash
 7608 ttys001    0:00.00 script
bash-5.0$ exit

Script done, output file is typescript
16-MacBook-Pro:~ nimeshneema$ 
```

**Ubuntu Linux**

```
nimeshneema@nimeshneema-Ubuntu:~$ ps
  PID TTY          TIME CMD
 1897 pts/0    00:00:00 bash
12363 pts/0    00:00:00 ps
nimeshneema@nimeshneema-Ubuntu:~$ script
Script started, file is typescript
nimeshneema@nimeshneema-Ubuntu:~$ ps
  PID TTY          TIME CMD
12365 pts/1    00:00:00 bash
12373 pts/1    00:00:00 ps
nimeshneema@nimeshneema-Ubuntu:~$ exit
Script done, file is typescript
nimeshneema@nimeshneema-Ubuntu:~$ 
```
